import { Language } from "../types/global";
import cataloniaFlag from "../assets/Flag_of_Catalonia.svg";

export const API_URL = "https://perfecttext.onrender.com/api";
export const API_URL_LOCAL = "http://localhost:3000/api";

export const STRIPE_ESTANDAR = "prod_RO65nOZ8xgE8Gs";
export const STRIPE_PREMIUM = "prod_RK0SNcBX9KfsC4";

export const mainLanguages: Language[] = [
  { code: "ES", name: "Español", flag: "https://flagcdn.com/es.svg" },
  { code: "EN", name: "English", flag: "https://flagcdn.com/gb.svg" },
  { code: "CA", name: "Català", flag: "img/Flag_of_Catalonia.svg" },
  { code: "FR", name: "Français", flag: "https://flagcdn.com/fr.svg" },
  // { code: "DE", name: "Deutsch", flag: "https://flagcdn.com/de.svg" },
];

export const mainLanguagesTrad: Language[] = [
  { code: "ES", name: "Español", flag: "https://flagcdn.com/es.svg" },
  { code: "EN", name: "English", flag: "https://flagcdn.com/gb.svg" },
  { code: "CA", name: "Català", flag: "img/Flag_of_Catalonia.svg" },
];

export const mainLanguagesTradDoc: Language[] = [
  { code: "ES", name: "Español", flag: "https://flagcdn.com/es.svg" },
  { code: "EN", name: "English", flag: "https://flagcdn.com/gb.svg" },
  { code: "FR", name: "Français", flag: "https://flagcdn.com/fr.svg" },
  { code: "DE", name: "Deutsch", flag: "https://flagcdn.com/de.svg" },
];

export const additionalLanguages: Language[] = [
  { code: "IT", name: "Italiano", flag: "https://flagcdn.com/it.svg" },
  { code: "ZH", name: "中文 (Chino)", flag: "https://flagcdn.com/cn.svg" },
  { code: "HI", name: "हिन्दी (Hindi)", flag: "https://flagcdn.com/in.svg" },
  { code: "AR", name: "العربية (Árabe)", flag: "https://flagcdn.com/sa.svg" },
  { code: "BN", name: "বাংলা (Bengalí)", flag: "https://flagcdn.com/bd.svg" },
  { code: "PT", name: "Português", flag: "https://flagcdn.com/pt.svg" },
  { code: "RU", name: "Русский (Ruso)", flag: "https://flagcdn.com/ru.svg" },
  { code: "JA", name: "日本語 (Japonés)", flag: "https://flagcdn.com/jp.svg" },
  { code: "TR", name: "Türkçe (Turco)", flag: "https://flagcdn.com/tr.svg" },
  { code: "KO", name: "한국어 (Coreano)", flag: "https://flagcdn.com/kr.svg" },
  {
    code: "VI",
    name: "Tiếng Việt (Vietnamita)",
    flag: "https://flagcdn.com/vn.svg",
  },
];

export const additionalLanguagesTrad: Language[] = [
  { code: "FR", name: "Français", flag: "https://flagcdn.com/fr.svg" },
  { code: "DE", name: "Deutsch", flag: "https://flagcdn.com/de.svg" },
  { code: "IT", name: "Italiano", flag: "https://flagcdn.com/it.svg" },
  { code: "ZH", name: "中文 (Chino)", flag: "https://flagcdn.com/cn.svg" },
  { code: "HI", name: "हिन्दी (Hindi)", flag: "https://flagcdn.com/in.svg" },
  { code: "AR", name: "العربية (Árabe)", flag: "https://flagcdn.com/sa.svg" },
  { code: "BN", name: "বাংলা (Bengalí)", flag: "https://flagcdn.com/bd.svg" },
  { code: "PT", name: "Português", flag: "https://flagcdn.com/pt.svg" },
  { code: "RU", name: "Русский (Ruso)", flag: "https://flagcdn.com/ru.svg" },
  { code: "JA", name: "日本語 (Japonés)", flag: "https://flagcdn.com/jp.svg" },
  { code: "TR", name: "Türkçe (Turco)", flag: "https://flagcdn.com/tr.svg" },
  { code: "KO", name: "한국어 (Coreano)", flag: "https://flagcdn.com/kr.svg" },
  {
    code: "VI",
    name: "Tiếng Việt (Vietnamita)",
    flag: "https://flagcdn.com/vn.svg",
  },
];

export const allLanguages: Language[] = [
  { code: "ES", name: "Español", flag: "https://flagcdn.com/es.svg" },
  { code: "EN", name: "English", flag: "https://flagcdn.com/gb.svg" },
  { code: "CA", name: "Català", flag: "img/Flag_of_Catalonia.svg" },
  { code: "FR", name: "Français", flag: "https://flagcdn.com/fr.svg" },
  { code: "DE", name: "Deutsch", flag: "https://flagcdn.com/de.svg" },
  { code: "IT", name: "Italiano", flag: "https://flagcdn.com/it.svg" },
  { code: "ZH", name: "中文 (Chino)", flag: "https://flagcdn.com/cn.svg" },
  { code: "HI", name: "हिन्दी (Hindi)", flag: "https://flagcdn.com/in.svg" },
  { code: "AR", name: "العربية (Árabe)", flag: "https://flagcdn.com/sa.svg" },
  { code: "BN", name: "বাংলা (Bengalí)", flag: "https://flagcdn.com/bd.svg" },
  { code: "PT", name: "Português", flag: "https://flagcdn.com/pt.svg" },
  { code: "RU", name: "Русский (Ruso)", flag: "https://flagcdn.com/ru.svg" },
  { code: "JA", name: "日本語 (Japonés)", flag: "https://flagcdn.com/jp.svg" },
  { code: "TR", name: "Türkçe (Turco)", flag: "https://flagcdn.com/tr.svg" },
  { code: "KO", name: "한국어 (Coreano)", flag: "https://flagcdn.com/kr.svg" },
  {
    code: "VI",
    name: "Tiếng Việt (Vietnamita)",
    flag: "https://flagcdn.com/vn.svg",
  },
];

const avatarOptions = [
  "https://api.dicebear.com/7.x/pixel-art/svg?seed=maria&size=128",
  "https://api.dicebear.com/7.x/pixel-art/svg?seed=ana&size=128",
  "https://api.dicebear.com/7.x/pixel-art/svg?seed=carlos&size=128",
  "https://api.dicebear.com/7.x/pixel-art/svg?seed=sofia&size=128",
  "https://api.dicebear.com/7.x/pixel-art/svg?seed=diego&size=128",
  "https://api.dicebear.com/7.x/pixel-art/svg?seed=laura&size=128",
  "https://api.dicebear.com/7.x/pixel-art/svg?seed=javier&size=128",
  "https://api.dicebear.com/7.x/pixel-art/svg?seed=emma&size=128",
  "https://api.dicebear.com/7.x/pixel-art/svg?seed=pablo&size=128",
  "https://api.dicebear.com/7.x/pixel-art/svg?seed=elena&size=128",
  "https://api.dicebear.com/7.x/pixel-art/svg?seed=alex&size=128",
  "https://api.dicebear.com/7.x/pixel-art/svg?seed=sara&size=128",
];

const universities = [
  "Universidad de Barcelona (UB)",
  "Universidad Autónoma de Barcelona (UAB)",
  "Universidad Politécnica de Cataluña (UPC)",
  "Universidad Pompeu Fabra (UPF)",
  "Universidad de Lleida (UdL)",
  "Universidad de Girona (UdG)",
  "Universidad Rovira i Virgili (URV)",
  "Universidad Abat Oliba CEU (UAO)",
  "Universidad Internacional de Cataluña (UIC)",
  "Universidad Europea de Barcelona (European University) (EU)",
  "Universidad Oberta de Cataluña (UOC)",
  "Harbour.Space University (HSU)",
  "Universidad de Vic - Universidad Central de Cataluña (UVic)",
  "Universidad de Alcalá (UAH)",
  "Universidad Alfonso X el Sabio (UAX)",
  "Universidad de Alicante (UA)",
  "Universidad de Almería (UAL)",
  "Universidad Internacional de Andalucía (UNIA)",
  "Universidad Católica de Ávila (UCAV)",
  "Atlantic-Mediterranean Technological University (ATU)",
  "Universidad Europea del Atlántico (UNEATLANTICO)",
  "Universidad del Atlántico Medio (UNAM)",
  "Universidad de las Islas Baleares (UIB)",
  "Universidad del País Vasco (UPV/EHU)",
  "Universidad de Burgos (UBU)",
  "Universidad de Cádiz (UCA)",
  "Universidad Camilo José Cela (UCJC)",
  "Universidad Europea de Canarias (UEC)",
  "Universidad de Cantabria (UC)",
  "Universidad Politécnica de Cartagena (UPCT)",
  "Universidad de Castilla-La Mancha (UCLM)",
  "Universidad CEU Cardenal Herrera (CEU-UCH)",
  "Universidad CEU San Pablo (CEU-SP)",
  "Universidad Carlos III de Madrid (UC3M)",
  "Universidad Pontificia Comillas (UPCO)",
  "Universidad de Córdoba (UCO)",
  "Universidad de A Coruña (UDC)",
  "Universidad de Deusto (UD)",
  "Universidad de Diseño, Innovación y Tecnología (UDIT)",
  "Universidad Nacional de Educación a Distancia (UNED)",
  "Universidad Miguel Hernández (UMH)",
  "ESIC University (ESIC)",
  "Universidad Europea de Madrid (UEM)",
  "Universidad Politécnica de Madrid (UPM)",
  "Universidad de Extremadura (UEX)",
  "Universidad Fernando III (UFIII)",
  "Universidad Fernando Pessoa Canarias (UFPC)",
  "Universidad Francisco de Vitoria (UFV)",
  "Universidad Complutense de Madrid (UCM)",
  "Universidad a Distancia de Madrid (UDIMA)",
  "Universidad de Málaga (UMA)",
  "Universidad de Murcia (UMU)",
  "Universidad Internacional Menéndez Pelayo (UIMP)",
  "Universidad Europea Miguel de Cervantes (UEMC)",
  "Mondragón Unibertsitatea (MU)",
  "Universidad de Navarra (UNAV)",
  "Universidad Pública de Navarra (UPNA)",
  "Universidad Nebrija (UNB)",
  "Universidad de Oviedo (UNIOVI)",
  "Universidad Pablo de Olavide (UPO)",
  "Universidad de Las Palmas de Gran Canaria (ULPGC)",
  "Universidad de Salamanca (USAL)",
  "Universidad Pontificia de Salamanca (UPSA)",
  "Universidad Católica San Antonio de Murcia (UCAM)",
  "Universidad San Dámaso (USD)",
  "Universidad San Jorge (USJ)",
  "Universidad Católica de Valencia San Vicente Mártir (UCV)",
  "Universidad de Santiago de Compostela (USC)",
  "Universidad de Sevilla (US)",
  "Universidad de Valencia (UV)",
  "Universidad Internacional Valenciana (VIU)",
  "Universidad Politécnica de Valencia (UPV)",
  "Universidad de Valladolid (UVA)",
  "Universidad de Vigo (UVIGO)",
  "Universidad Villanueva (UVILL)",
  "Universidad de Zaragoza (UNIZAR)",
];

const majors = [
  // Ciencias Sociales y Humanidades
  "Administración y Dirección de Empresas",
  "Administración y Gestión Pública",
  "Antropología",
  "Ciberseguridad",
  "Ciencias Políticas",
  "Comunicación Audiovisual",
  "Criminología",
  "Derecho",
  "Economía",
  "Filosofía",
  "Geografía",
  "Historia",
  "Historia del Arte",
  "Lenguas Modernas",
  "Lingüística",
  "Literatura",
  "Marketing e Investigación de Mercados",
  "Periodismo",
  "Psicología",
  "Publicidad y Relaciones Públicas",
  "Relaciones Laborales y Recursos Humanos",
  "Relaciones Internacionales",
  "Sociología",
  "Traducción e Interpretación",
  "Turismo",
  "Trabajo Social",
  "Educación Infantil",
  "Pedagogía",
  "Magisterio",
  "Educación Social",
  "Educación Primaria",

  // Ciencias de la Salud
  "Ciencias Biomédicas",
  "Ciencias de la Actividad Física y del Deporte",
  "Enfermería",
  "Farmacia",
  "Fisioterapia",
  "Logopedia",
  "Medicina",
  "Nutrición Humana y Dietética",
  "Odontología",
  "Óptica y Optometría",
  "Podología",
  "Psicología",
  "Terapia Ocupacional",
  "Veterinaria",

  // Ciencias Experimentales
  "Bioinformática",
  "Bioingeniería",
  "Biología",
  "Biomedicina",
  "Bioquímica",
  "Biotecnología",
  "Ciencia e Ingeniería de Datos",
  "Ciencia de los Alimentos",
  "Ciencias Ambientales",
  "Ciencias del Mar",
  "Estadística",
  "Física",
  "Geología",
  "Matemáticas",
  "Química",
  "Ciencias Actuariales y Financieras",

  // Arte y Humanidades
  "Animación",
  "Arqueología",
  "Arquitectura",
  "Arquitectura Naval",
  "Ingeniería Marítima",
  "Arte",
  "Bellas Artes",
  "Conservación y Restauración",
  "Diseño",
  "Diseño Gráfico",
  "Diseño de Interiores",
  "Diseño de Moda",
  "Estudios Ingleses",
  "Filología Clásica",
  "Filología Hispánica",
  "Historia y Ciencias de la Música",
  "Musicología",
  "Teoría de la Literatura",

  // Ingenierías
  "Arquitectura Técnica",
  "Edificación",
  "Ingeniería Aeroespacial",
  "Ingeniería Agroambiental",
  "Ingeniería Agrícola",
  "Ingeniería Agrónoma",
  "Ingeniería Alimentaria",
  "Ingeniería Biomédica",
  "Ingeniería Civil",
  "Ingeniería de Caminos",
  "Ingeniería de Materiales",
  "Ingeniería de Minas",
  "Ingeniería de Montes",
  "Ingeniería de Sistemas",
  "Ingeniería de Telecomunicación",
  "Ingeniería Electrónica",
  "Ingeniería Eléctrica",
  "Ingeniería en Energía",
  "Ingeniería Forestal",
  "Ingeniería Geológica",
  "Ingeniería Geomática",
  "Ingeniería Informática",
  "Ingeniería Industrial",
  "Ingeniería Mecánica",
  "Ingeniería Naval",
  "Ingeniería Nuclear",
  "Ingeniería Química",
  "Ingeniería en Organización Industrial",
  "Ingeniería en Tecnologías Industriales",
  "Diseño Industrial y Desarrollo del Producto",

  // Otras especialidades
  "Ciencias Náuticas",
  "Gestión Aeronáutica",
  "Logística",
  "Protocolo y Organización de Eventos",
  "Seguridad",
  "Ciencias del Transporte",
  "Estudios de Asia Oriental",
  "Estudios Árabes e Islámicos",
  "Estudios Hebreos y Arameos",
];

const yearOptions = [
  "1º Curso",
  "2º Curso",
  "3º Curso",
  "4º Curso",
  "5º Curso",
  "6º Curso",
  "Máster",
  "Doctorado",
];
